name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  security:
    name: Security
    uses: ./.github/workflows/security.yaml
    secrets: inherit
 
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: "corretto"
            java-version: "11"
            cache: maven
        - run: mvn -B -Pgithub package --file pom.xml
